# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  pomaps-benchmarks:
    dependencies:
    - base
    - pomaps
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Data Structures
description: Maps and sets indexed by a partial order
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: sgraf812/pomaps
library:
  dependencies:
  - base
  - ghc-prim
  - lattices >= 1.6.0
  - containers >= 0.5.9.2
  source-dirs: library
license: MIT
maintainer: Sebastian Graf
name: pomaps
synopsis: Maps and set indexed by a partial order
tests:
  pomaps-test-suite:
    dependencies:
    - base
    - containers
    - pomaps
    - lattices >= 1.6.0
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
